"""add description to task

Revision ID: 22c6cd07e29b
Revises: cee8d027893c
Create Date: 2025-04-18 15:15:58.875030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c6cd07e29b'
down_revision: Union[str, None] = 'cee8d027893c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('description', sa.String(), nullable=False, server_default='Tarefa sem descrição'))
    op.drop_column('task', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('task', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('task', 'description')
    # ### end Alembic commands ###
