"""add completed_at to task_status

Revision ID: fcedf6f2f446
Revises: 22c6cd07e29b
Create Date: 2025-05-21 18:54:54.093617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcedf6f2f446'
down_revision: Union[str, None] = '22c6cd07e29b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_status', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_status', 'completed_at')
    # ### end Alembic commands ###
